version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to DockerHub...
      - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
      - REPOSITORY_URI="docker.io/aishwaryavaithiyanathan/backend"
      - CONTAINER_NAME="backend"
      - IMAGE_TAG="latest"

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - export DOCKER_BUILDKIT=0
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the image to DockerHub...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - echo "[{\"name\":\"$CONTAINER_NAME\",\"imageUri\":\"$REPOSITORY_URI:$IMAGE_TAG\"}]" > imagedefinition.json
      - cat imagedefinition.json
      - ls -l imagedefinition.json
      - pwd
      - ls -R

artifacts:
  files:
    - imagedefinition.json
